---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ geth_expo_cont_name }}'
    consul_services:
      # Prometheus config expects this service name
      - id:   '{{ geth_expo_cont_name }}'
        name: '{{ geth_expo_consul_service_name }}'
        tags: '{{ geth_expo_consul_tags }}'
        port: '{{ geth_expo_cont_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        meta:
          container: '{{ geth_expo_source_cont_name | mandatory }}'
        checks:
          - id: '{{ geth_expo_cont_name }}-health'
            name: '{{ geth_expo_consul_service_name }} healthcheck'
            type: 'http'
            http: 'http://localhost:{{ geth_expo_cont_port }}/health'
