---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ geth_expo_cont_name | replace("-", "_") }}'
    consul_services:
      - name: '{{ geth_expo_consul_name }}'
        port: '{{ geth_expo_cont_port }}'
        address: '{{ geth_expo_consul_addr }}'
        tags: '{{ geth_expo_consul_tags }}'
        meta:
          container: '{{ geth_source_cont_name | mandatory }}'
        checks:
          - id: '{{ geth_expo_consul_name }}-health'
            name: 'geth-exporter healthcheck'
            type: http
            http: 'http://localhost:{{ geth_expo_cont_port }}/health'
