---
- name: 'Start container: {{ geth_expo_cont_name }}'
  docker_container:
    name: '{{ geth_expo_cont_name }}'
    image: '{{ geth_expo_cont_image }}'
    user: root
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: geth_exporter 
    volumes_from: '{{ geth_source_cont_name | mandatory }}'
    command: |
      -ipc {{ geth_source_cont_ipc_path }}
      -port 9200
    ports:
      - '{{ geth_expo_cont_port }}:9200/tcp'
